SELECT productkey,
       productalternatekey,
       productsubcategorykey,
       weightunitmeasurecode,
       sizeunitmeasurecode,
       englishproductname,
       spanishproductname,
       frenchproductname,
       standardcost,
       finishedgoodsflag,
       color,
       safetystocklevel,
       reorderpoint,
       listprice,
       chinesedescription,
       arabicdescription,
       hebrewdescription,
       thaidescription,
       germandescription,
       japanesedescription,
       turkishdescription,
       startdate,
       enddate,
       [status]
FROM   adventureworksdw2019.dbo.dimproduct 